apiVersion: apps/v1
kind: Deployment
metadata:
  name: mci-frontend
  labels:
    app: mci-frontend
spec:
  selector:
    matchLabels:
      app: mci-frontend
  template:
    metadata:
      labels:
        app: mci-frontend
    spec:
      containers:
      - name: myfrontend
        image: sekhrivijay/mci-test:v3
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "0.2Gi"
            cpu: "0.3"
          limits:
            memory: "0.2Gi"
            cpu: "0.4"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mci-frontend
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mci-frontend
  targetCPUUtilizationPercentage: 20
