apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-ingress
  labels:
    app: zoneprinter
spec:
  selector:
    matchLabels:
      app: zoneprinter
  template:
    metadata:
      labels:
        app: zoneprinter
    spec:
      containers:
      - name: myzp
        image: gcr.io/google-samples/zone-printer:0.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "0.2Gi"
            cpu: "0.2"
          limits:
            memory: "0.2Gi"
            cpu: "0.3"


---
apiVersion: v1
kind: Service
metadata:
  name: zone-printer-service
  labels:
    app: zone-printer-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: zoneprinter
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zone-ingress
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zone-ingress
  targetCPUUtilizationPercentage: 50
